
PAYLOAD = b"X5O!P%@AP[4\\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*"


EMBED_OFFSET = 87531


MYSTERY_PAYLOAD = b"DEMO-UNKNOWN-PAYLOAD-NOT-EICAR-SIGNATURE-XYZ123-STRUCTUR"


NUM_EICAR_LOCATIONS = 2
NUM_MYSTERY_LOCATIONS = 3